let money = 1200;
console.log(money);
let income = 'ebay';
console.log(income);
let addExpenses = 'Appartment, Insurance, Loan';
console.log(addExpenses.length);
console.log(addExpenses.toLowerCase());
console.log(addExpenses.split(', '));
let deposit = true;
console.log(deposit);
let mission = 25;
let period = 7;
let budgetDay = 40;
console.log(budgetDay);